"""add posts

Revision ID: 852f288dc09e
Revises: d92b3b65ccdd
Create Date: 2017-01-11 01:15:37.722396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852f288dc09e'
down_revision = 'd92b3b65ccdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_edit', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_posts_last_edit'), 'posts', ['last_edit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_last_edit'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
